Message.create(content: "Hello, how are you?")
Message.create(content: "Hi there! How can I help you today?")
Message.create(content: "Good morning! Have a great day.")
Message.create(content: "Hey, it's nice to see you!")
Message.create(content: "Welcome! Feel free to ask any questions.")